//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKHeX.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PKHeX.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Kein
        ///Meisterball
        ///Hyperball
        ///Superball
        ///Pokéball
        ///Safariball
        ///Netzball
        ///Tauchball
        ///Nestball
        ///Wiederball
        ///Timerball
        ///Luxusball
        ///Premierball
        ///Finsterball
        ///Heilball
        ///Flottball
        ///Jubelball
        ///Trank
        ///Gegengift
        ///Feuerheiler
        ///Eisheiler
        ///Aufwecker
        ///Para-Heiler
        ///Top-Genesung
        ///Top-Trank
        ///Hypertrank
        ///Supertrank
        ///Hyperheiler
        ///Beleber
        ///Top-Beleber
        ///Tafelwasser
        ///Sprudel
        ///Limonade
        ///Kuhmuh-Milch
        ///Energiestaub
        ///Kraftwurzel
        ///Heilpuder
        ///Vitalkraut
        ///Äther
        ///Top-Äther
        ///Elixier
        ///Top-Elixier
        ///Lavakeks
        ///Beerensaft
        ///Zauberasche
        ///KP-Pl [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_de {
            get {
                return ResourceManager.GetString("text_Items_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None
        ///Master Ball
        ///Ultra Ball
        ///Great Ball
        ///Poké Ball
        ///Safari Ball
        ///Net Ball
        ///Dive Ball
        ///Nest Ball
        ///Repeat Ball
        ///Timer Ball
        ///Luxury Ball
        ///Premier Ball
        ///Dusk Ball
        ///Heal Ball
        ///Quick Ball
        ///Cherish Ball
        ///Potion
        ///Antidote
        ///Burn Heal
        ///Ice Heal
        ///Awakening
        ///Paralyze Heal
        ///Full Restore
        ///Max Potion
        ///Hyper Potion
        ///Super Potion
        ///Full Heal
        ///Revive
        ///Max Revive
        ///Fresh Water
        ///Soda Pop
        ///Lemonade
        ///Moomoo Milk
        ///Energy Powder
        ///Energy Root
        ///Heal Powder
        ///Revival Herb
        ///Ether
        ///Max Ether
        ///Elixir
        ///Max Elixir
        ///Lava Cookie
        ///Berry Juice [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_en {
            get {
                return ResourceManager.GetString("text_Items_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ningún objeto
        ///Master Ball
        ///Ultra Ball
        ///Super Ball
        ///Poké Ball
        ///Safari Ball
        ///Malla Ball
        ///Buceo Ball
        ///Nido Ball
        ///Acopio Ball
        ///Turno Ball
        ///Lujo Ball
        ///Honor Ball
        ///Ocaso Ball
        ///Sana Ball
        ///Veloz Ball
        ///Gloria Ball
        ///Poción
        ///Antídoto
        ///Antiquemar
        ///Antihielo
        ///Despertar
        ///Antiparalizador
        ///Restaurar Todo
        ///Poción Máxima
        ///Hiperpoción
        ///Superpoción
        ///Cura Total
        ///Revivir
        ///Revivir Máximo
        ///Agua Fresca
        ///Refresco
        ///Limonada
        ///Leche Mu-mu
        ///Polvo Energía
        ///Raíz Energía
        ///Polvo Curación
        ///Hierba Revivir
        ///Éter
        ///Éter Máximo
        ///Elixir
        ///Elixir M [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_es {
            get {
                return ResourceManager.GetString("text_Items_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aucun
        ///Master Ball
        ///Hyper Ball
        ///Super Ball
        ///Poké Ball
        ///Safari Ball
        ///Filet Ball
        ///Scuba Ball
        ///Faiblo Ball
        ///Bis Ball
        ///Chrono Ball
        ///Luxe Ball
        ///Honor Ball
        ///Sombre Ball
        ///Soin Ball
        ///Rapide Ball
        ///Mémoire Ball
        ///Potion
        ///Antidote
        ///Anti-Brûle
        ///Antigel
        ///Réveil
        ///Anti-Para
        ///Guérison
        ///Potion Max
        ///Hyper Potion
        ///Super Potion
        ///Total Soin
        ///Rappel
        ///Rappel Max
        ///Eau Fraîche
        ///Soda Cool
        ///Limonade
        ///Lait Meumeu
        ///Poudrénergie
        ///Racinénergie
        ///Poudre Soin
        ///Herbe Rappel
        ///Huile
        ///Huile Max
        ///Élixir
        ///Élixir Max
        ///Lava Cookie
        ///Jus de Baie
        ///Cend [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_fr {
            get {
                return ResourceManager.GetString("text_Items_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Niente
        ///Master Ball
        ///Ultra Ball
        ///Mega Ball
        ///Poké Ball
        ///Safari Ball
        ///Rete Ball
        ///Sub Ball
        ///Minor Ball
        ///Bis Ball
        ///Timer Ball
        ///Chic Ball
        ///Premier Ball
        ///Scuro Ball
        ///Cura Ball
        ///Velox Ball
        ///Pregio Ball
        ///Pozione
        ///Antidoto
        ///Antiscottatura
        ///Antigelo
        ///Sveglia
        ///Antiparalisi
        ///Ricarica totale
        ///Pozione max
        ///Iperpozione
        ///Superpozione
        ///Cura totale
        ///Revitalizzante
        ///Revitalizzante max
        ///Acqua fresca
        ///Gassosa
        ///Lemonsucco
        ///Latte Mumu
        ///Polvenergia
        ///Radicenergia
        ///Polvocura
        ///Vitalerba
        ///Etere
        ///Etere max
        ///Elisir
        ///Elisir max
        ///Lavottin [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_it {
            get {
                return ResourceManager.GetString("text_Items_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 なし
        ///マスターボール
        ///ハイパーボール
        ///スーパーボール
        ///モンスターボール
        ///サファリボール
        ///ネットボール
        ///ダイブボール
        ///ネストボール
        ///リピートボール
        ///タイマーボール
        ///ゴージャスボール
        ///プレミアボール
        ///ダークボール
        ///ヒールボール
        ///クイックボール
        ///プレシャスボール
        ///キズぐすり
        ///どくけし
        ///やけどなおし
        ///こおりなおし
        ///ねむけざまし
        ///まひなおし
        ///かいふくのくすり
        ///まんたんのくすり
        ///すごいキズぐすり
        ///いいキズぐすり
        ///なんでもなおし
        ///げんきのかけら
        ///げんきのかたまり
        ///おいしいみず
        ///サイコソーダ
        ///ミックスオレ
        ///モーモーミルク
        ///ちからのこな
        ///ちからのねっこ
        ///ばんのうごな
        ///ふっかつそう
        ///ピーピーエイド
        ///ピーピーリカバー
        ///ピーピーエイダー
        ///ピーピーマックス
        ///フエンせんべい
        ///きのみジュース
        ///せいなるはい
        ///マックスアップ
        ///タウリン
        ///ブロムヘキシン
        ///インドメタシン
        ///リゾチウム
        ///ふしぎなアメ
        ///ポイントアップ
        ///キトサン
        ///ポイントマックス
        ///もりのヨウカン
        ///エフェクトガード
        ///クリティカット
        ///プラスパワー
        ///ディフェンダー
        ///スピーダー        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_ja {
            get {
                return ResourceManager.GetString("text_Items_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 없음
        ///마스터볼
        ///하이퍼볼
        ///슈퍼볼
        ///몬스터볼
        ///사파리볼
        ///네트볼
        ///다이브볼
        ///네스트볼
        ///리피트볼
        ///타이머볼
        ///럭셔리볼
        ///프리미어볼
        ///다크볼
        ///힐볼
        ///퀵볼
        ///프레셔스볼
        ///상처약
        ///해독제
        ///화상치료제
        ///얼음상태치료제
        ///잠깨는약
        ///마비치료제
        ///회복약
        ///풀회복약
        ///고급상처약
        ///좋은상처약
        ///만병통치제
        ///기력의조각
        ///기력의덩어리
        ///맛있는물
        ///미네랄사이다
        ///후르츠밀크
        ///튼튼밀크
        ///힘의가루
        ///힘의뿌리
        ///만능가루
        ///부활초
        ///PP에이드
        ///PP회복
        ///PP에이더
        ///PP맥스
        ///용암전병
        ///나무열매쥬스
        ///성스러운분말
        ///맥스업
        ///타우린
        ///사포닌
        ///알칼로이드
        ///리보플라빈
        ///이상한사탕
        ///포인트업
        ///키토산
        ///포인트맥스
        ///숲의양갱
        ///이펙트가드
        ///크리티컬커터
        ///플러스파워
        ///디펜드업
        ///스피드업
        ///잘-맞히기
        ///스페셜업
        ///스페셜가드
        ///삐삐인형
        ///에나비꼬리
        ///파랑비드로
        ///노랑비드로
        ///빨강비드로
        ///검정비드로
        ///하양비드로
        ///여울소금
        ///여울조개껍질
        ///빨강조각
        ///파랑조각
        ///노랑조각
        ///초록조각
        ///실버스프레이
        ///골드스프레이
        ///동굴탈출로프
        ///벌레회피스프레이        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_ko {
            get {
                return ResourceManager.GetString("text_Items_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无
        ///大师球
        ///高级球
        ///超级球
        ///精灵球
        ///狩猎球
        ///捕网球
        ///潜水球
        ///巢穴球
        ///重复球
        ///计时球
        ///豪华球
        ///纪念球
        ///黑暗球
        ///治愈球
        ///先机球
        ///贵重球
        ///伤药
        ///解毒药
        ///灼伤药
        ///解冻药
        ///解眠药
        ///解麻药
        ///全复药
        ///全满药
        ///厉害伤药
        ///好伤药
        ///万灵药
        ///活力碎片
        ///活力块
        ///美味之水
        ///劲爽汽水
        ///果汁牛奶
        ///哞哞鲜奶
        ///元气粉
        ///元气根
        ///万能粉
        ///复活草
        ///ＰＰ单项小补剂
        ///ＰＰ单项全补剂
        ///ＰＰ多项小补剂
        ///ＰＰ多项全补剂
        ///釜炎仙贝
        ///树果汁
        ///圣灰
        ///ＨＰ增强剂
        ///攻击增强剂
        ///防御增强剂
        ///速度增强剂
        ///特攻增强剂
        ///神奇糖果
        ///ＰＰ提升剂
        ///特防增强剂
        ///ＰＰ极限提升剂
        ///森之羊羹
        ///能力防守
        ///要害攻击
        ///力量强化
        ///防御强化
        ///速度强化
        ///命中强化
        ///特攻强化
        ///特防强化
        ///皮皮玩偶
        ///向尾喵的尾巴
        ///蓝色玻璃哨
        ///黄色玻璃哨
        ///红色玻璃哨
        ///黑色玻璃哨
        ///白色玻璃哨
        ///浅滩海盐
        ///浅滩贝壳
        ///红色碎片
        ///蓝色碎片
        ///黄色碎片
        ///绿色碎片
        ///白银喷雾
        ///黄金喷雾
        ///离洞绳
        ///除虫喷雾
        ///日之石
        ///月之石
        ///火之石
        ///雷之石
        ///水之石
        ///叶之石
        ///小蘑菇
        ///大蘑菇
        ///珍珠 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_zh_Hans {
            get {
                return ResourceManager.GetString("text_Items_zh_Hans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無
        ///大師球
        ///高級球
        ///超級球
        ///精靈球
        ///狩獵球
        ///捕網球
        ///潛水球
        ///巢穴球
        ///重複球
        ///計時球
        ///豪華球
        ///紀念球
        ///黑暗球
        ///治癒球
        ///先機球
        ///貴重球
        ///傷藥
        ///解毒藥
        ///灼傷藥
        ///解凍藥
        ///解眠藥
        ///解麻藥
        ///全復藥
        ///全滿藥
        ///厲害傷藥
        ///好傷藥
        ///萬靈藥
        ///活力碎片
        ///活力塊
        ///美味之水
        ///勁爽汽水
        ///果汁牛奶
        ///哞哞鮮奶
        ///元氣粉
        ///元氣根
        ///萬能粉
        ///復活草
        ///ＰＰ單項小補劑
        ///ＰＰ單項全補劑
        ///ＰＰ多項小補劑
        ///ＰＰ多項全補劑
        ///釜炎仙貝
        ///樹果汁
        ///聖灰
        ///ＨＰ增強劑
        ///攻擊增強劑
        ///防禦增強劑
        ///速度增強劑
        ///特攻增強劑
        ///神奇糖果
        ///ＰＰ提升劑
        ///特防增強劑
        ///ＰＰ極限提升劑
        ///森之羊羹
        ///能力防守
        ///要害攻擊
        ///力量強化
        ///防禦強化
        ///速度強化
        ///命中強化
        ///特攻強化
        ///特防強化
        ///皮皮玩偶
        ///向尾喵的尾巴
        ///藍色玻璃哨
        ///黃色玻璃哨
        ///紅色玻璃哨
        ///黑色玻璃哨
        ///白色玻璃哨
        ///淺灘海鹽
        ///淺灘貝殼
        ///紅色碎片
        ///藍色碎片
        ///黃色碎片
        ///綠色碎片
        ///白銀噴霧
        ///黃金噴霧
        ///離洞繩
        ///除蟲噴霧
        ///日之石
        ///月之石
        ///火之石
        ///雷之石
        ///水之石
        ///葉之石
        ///小蘑菇
        ///大蘑菇
        ///珍珠 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_zh_Hant {
            get {
                return ResourceManager.GetString("text_Items_zh_Hant", resourceCulture);
            }
        }
    }
}
