//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKHeX.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PKHeX.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ―
        ///恶臭
        ///降雨
        ///加速
        ///战斗盔甲
        ///结实
        ///湿气
        ///柔软
        ///沙隐
        ///静电
        ///蓄电
        ///储水
        ///迟钝
        ///无关天气
        ///复眼
        ///不眠
        ///变色
        ///免疫
        ///引火
        ///鳞粉
        ///我行我素
        ///吸盘
        ///威吓
        ///踩影
        ///粗糙皮肤
        ///神奇守护
        ///飘浮
        ///孢子
        ///同步
        ///恒净之躯
        ///自然回复
        ///避雷针
        ///天恩
        ///悠游自如
        ///叶绿素
        ///发光
        ///复制
        ///大力士
        ///毒刺
        ///精神力
        ///熔岩铠甲
        ///水幕
        ///磁力
        ///隔音
        ///雨盘
        ///扬沙
        ///压迫感
        ///厚脂肪
        ///早起
        ///火焰之躯
        ///逃跑
        ///锐利目光
        ///怪力钳
        ///捡拾
        ///懒惰
        ///活力
        ///迷人之躯
        ///正电
        ///负电
        ///阴晴不定
        ///黏着
        ///蜕皮
        ///毅力
        ///神奇鳞片
        ///污泥浆
        ///茂盛
        ///猛火
        ///激流
        ///虫之预感
        ///坚硬脑袋
        ///日照
        ///沙穴
        ///干劲
        ///白色烟雾
        ///瑜伽之力
        ///硬壳盔甲
        ///气闸
        ///蹒跚
        ///电气引擎
        ///斗争心
        ///不屈之心
        ///雪隐
        ///贪吃鬼
        ///愤怒穴位
        ///轻装
        ///耐热
        ///单纯
        ///干燥皮肤
        ///下载
        ///铁拳
        ///毒疗
        ///适应力
        ///连续攻击
        ///湿润之躯
        ///太阳之力
        ///飞毛腿
        ///一般皮肤
        ///狙击手
        ///魔法防守
        ///无防守
        ///慢出
        ///技术高手
        ///叶子防守
        ///笨拙
        ///破格
        ///超幸运
        ///诱爆
        ///危险预知
        ///预知梦        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Abilities_zh {
            get {
                return ResourceManager.GetString("text_Abilities_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ―
        ///惡臭
        ///降雨
        ///加速
        ///戰鬥盔甲
        ///結實
        ///濕氣
        ///柔軟
        ///沙隱
        ///靜電
        ///蓄電
        ///儲水
        ///遲鈍
        ///無關天氣
        ///複眼
        ///不眠
        ///變色
        ///免疫
        ///引火
        ///鱗粉
        ///我行我素
        ///吸盤
        ///威嚇
        ///踩影
        ///粗糙皮膚
        ///神奇守護
        ///飄浮
        ///孢子
        ///同步
        ///恆淨之軀
        ///自然回復
        ///避雷針
        ///天恩
        ///悠游自如
        ///葉綠素
        ///發光
        ///複製
        ///大力士
        ///毒刺
        ///精神力
        ///熔岩鎧甲
        ///水幕
        ///磁力
        ///隔音
        ///雨盤
        ///揚沙
        ///壓迫感
        ///厚脂肪
        ///早起
        ///火焰之軀
        ///逃跑
        ///銳利目光
        ///怪力鉗
        ///撿拾
        ///懶惰
        ///活力
        ///迷人之軀
        ///正電
        ///負電
        ///陰晴不定
        ///黏著
        ///蛻皮
        ///毅力
        ///神奇鱗片
        ///污泥漿
        ///茂盛
        ///猛火
        ///激流
        ///蟲之預感
        ///堅硬腦袋
        ///日照
        ///沙穴
        ///幹勁
        ///白色煙霧
        ///瑜伽之力
        ///硬殼盔甲
        ///氣閘
        ///蹣跚
        ///電氣引擎
        ///鬥爭心
        ///不屈之心
        ///雪隱
        ///貪吃鬼
        ///憤怒穴位
        ///輕裝
        ///耐熱
        ///單純
        ///乾燥皮膚
        ///下載
        ///鐵拳
        ///毒療
        ///適應力
        ///連續攻擊
        ///濕潤之軀
        ///太陽之力
        ///飛毛腿
        ///一般皮膚
        ///狙擊手
        ///魔法防守
        ///無防守
        ///慢出
        ///技術高手
        ///葉子防守
        ///笨拙
        ///破格
        ///超幸運
        ///引爆
        ///危險預知
        ///預知夢        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Abilities_zh2 {
            get {
                return ResourceManager.GetString("text_Abilities_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非常喜欢吃东西。
        ///经常睡午觉。
        ///常常打瞌睡。
        ///经常乱扔东西。
        ///喜欢悠然自在。
        ///以力气大为傲。
        ///喜欢胡闹。
        ///有点容易生气。
        ///喜欢打架。
        ///血气方刚。
        ///身体强壮。
        ///抗打能力强。
        ///顽强不屈。
        ///能吃苦耐劳。
        ///善于忍耐。
        ///喜欢比谁跑得快。
        ///对声音敏感。
        ///冒冒失失。
        ///有点容易得意忘形。
        ///逃得快。
        ///好奇心强。
        ///喜欢恶作剧。
        ///做事万无一失。
        ///经常思考。
        ///一丝不苟。
        ///性格强势。
        ///有一点点爱慕虚荣。
        ///争强好胜。
        ///不服输。
        ///有一点点固执。 的本地化字符串。
        /// </summary>
        internal static string text_Character_zh {
            get {
                return ResourceManager.GetString("text_Character_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非常喜歡吃東西。
        ///經常睡午覺。
        ///常常打瞌睡。
        ///經常亂扔東西。
        ///喜歡悠然自在。
        ///以力氣大為傲。
        ///喜歡胡鬧。
        ///有點容易生氣。
        ///喜歡打架。
        ///血氣方剛。
        ///身體強壯。
        ///抗打能力強。
        ///頑強不屈。
        ///能吃苦耐勞。
        ///善於忍耐。
        ///喜歡比誰跑得快。
        ///對聲音敏感。
        ///冒冒失失。
        ///有點容易得意忘形。
        ///逃得快。
        ///好奇心強。
        ///喜歡惡作劇。
        ///做事萬無一失。
        ///經常思考。
        ///一絲不茍。
        ///性格強勢。
        ///有一點點愛慕虛榮。
        ///爭強好勝。
        ///不服輸。
        ///有一點點固執。 的本地化字符串。
        /// </summary>
        internal static string text_Character_zh2 {
            get {
                return ResourceManager.GetString("text_Character_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刺刺耳皮丘
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///某种样子
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Forms_zh {
            get {
                return ResourceManager.GetString("text_Forms_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刺刺耳皮丘
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///某種樣子
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Forms_zh2 {
            get {
                return ResourceManager.GetString("text_Forms_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///蓝宝石
        ///红宝石
        ///绿宝石
        ///火红
        ///叶绿
        ///
        ///心金
        ///魂银
        ///
        ///钻石
        ///珍珠
        ///白金
        ///
        ///
        ///竞技场/XD
        ///
        ///
        ///
        ///
        ///白
        ///黑
        ///白 2
        ///黑 2
        ///X
        ///Y
        ///始源蓝宝石
        ///终极红宝石
        ///
        ///
        ///太阳
        ///月亮
        ///究极之日
        ///究极之月
        ///GO
        ///红
        ///蓝 [国际]/绿 [日]
        ///蓝 [日]
        ///黄
        ///金
        ///银
        ///水晶
        ///Let&apos;s Go！皮卡丘
        ///Let&apos;s Go！伊布
        ///剑
        ///盾
        ///
        ///传说 阿尔宙斯
        ///晶灿钻石
        ///明亮珍珠
        ///朱
        ///紫 的本地化字符串。
        /// </summary>
        internal static string text_Games_zh {
            get {
                return ResourceManager.GetString("text_Games_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///藍寶石
        ///紅寶石
        ///綠寶石
        ///火紅
        ///葉綠
        ///
        ///心金
        ///魂銀
        ///
        ///鑽石
        ///珍珠
        ///白金
        ///
        ///
        ///圓形競技場/XD旋風
        ///
        ///
        ///
        ///
        ///白
        ///黑
        ///白 2
        ///黑 2
        ///X
        ///Y
        ///阿爾法藍寶石
        ///歐米加紅寶石
        ///
        ///
        ///太陽
        ///月亮
        ///究極之日
        ///究極之月
        ///GO
        ///紅
        ///藍 [國際]/綠 [日]
        ///藍 [日]
        ///皮卡丘（黃）
        ///金
        ///銀
        ///水晶
        ///Let&apos;s Go！皮卡丘
        ///Let&apos;s Go！伊布
        ///劍
        ///盾
        ///
        ///傳說：阿爾宙斯
        ///晶燦鑽石
        ///明亮珍珠
        ///朱
        ///紫 的本地化字符串。
        /// </summary>
        internal static string text_Games_zh2 {
            get {
                return ResourceManager.GetString("text_Games_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无
        ///碎岩 (HGSS)
        ///高草丛
        ///
        ///帝牙卢卡/帕路奇亚
        ///洞穴/初始之间
        ///
        ///冲浪/钓鱼
        ///
        ///博物馆/神秘水晶
        ///大湿地/狩猎
        ///
        ///御三家/化石/礼物 (DP)
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///毁坏的世界(Pt)
        ///御三家/化石/礼物 (Pt/DP Trio) 的本地化字符串。
        /// </summary>
        internal static string text_GroundTile_zh {
            get {
                return ResourceManager.GetString("text_GroundTile_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無
        ///碎岩 (HGSS)
        ///高草叢
        ///
        ///帝牙盧卡/帕路奇亞
        ///洞穴/初始之間
        ///
        ///衝浪/釣魚
        ///
        ///博物館/神秘水晶
        ///大濕地/狩獵
        ///
        ///初始夥伴/化石/禮物 (DP)
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///毀壞的世界(Pt)
        ///初始夥伴/化石/禮物 (Pt/DP Trio) 的本地化字符串。
        /// </summary>
        internal static string text_GroundTile_zh2 {
            get {
                return ResourceManager.GetString("text_GroundTile_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kein
        ///Meisterball
        ///Hyperball
        ///Superball
        ///Pokéball
        ///Safariball
        ///Netzball
        ///Tauchball
        ///Nestball
        ///Wiederball
        ///Timerball
        ///Luxusball
        ///Premierball
        ///Finsterball
        ///Heilball
        ///Flottball
        ///Jubelball
        ///Trank
        ///Gegengift
        ///Feuerheiler
        ///Eisheiler
        ///Aufwecker
        ///Para-Heiler
        ///Top-Genesung
        ///Top-Trank
        ///Hypertrank
        ///Supertrank
        ///Hyperheiler
        ///Beleber
        ///Top-Beleber
        ///Tafelwasser
        ///Sprudel
        ///Limonade
        ///Kuhmuh-Milch
        ///Energiestaub
        ///Kraftwurzel
        ///Heilpuder
        ///Vitalkraut
        ///Äther
        ///Top-Äther
        ///Elixier
        ///Top-Elixier
        ///Lavakeks
        ///Beerensaft
        ///Zauberasche
        ///KP-Pl [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_de {
            get {
                return ResourceManager.GetString("text_Items_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None
        ///Master Ball
        ///Ultra Ball
        ///Great Ball
        ///Poké Ball
        ///Safari Ball
        ///Net Ball
        ///Dive Ball
        ///Nest Ball
        ///Repeat Ball
        ///Timer Ball
        ///Luxury Ball
        ///Premier Ball
        ///Dusk Ball
        ///Heal Ball
        ///Quick Ball
        ///Cherish Ball
        ///Potion
        ///Antidote
        ///Burn Heal
        ///Ice Heal
        ///Awakening
        ///Paralyze Heal
        ///Full Restore
        ///Max Potion
        ///Hyper Potion
        ///Super Potion
        ///Full Heal
        ///Revive
        ///Max Revive
        ///Fresh Water
        ///Soda Pop
        ///Lemonade
        ///Moomoo Milk
        ///Energy Powder
        ///Energy Root
        ///Heal Powder
        ///Revival Herb
        ///Ether
        ///Max Ether
        ///Elixir
        ///Max Elixir
        ///Lava Cookie
        ///Berry Juice [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_en {
            get {
                return ResourceManager.GetString("text_Items_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ningún objeto
        ///Master Ball
        ///Ultra Ball
        ///Super Ball
        ///Poké Ball
        ///Safari Ball
        ///Malla Ball
        ///Buceo Ball
        ///Nido Ball
        ///Acopio Ball
        ///Turno Ball
        ///Lujo Ball
        ///Honor Ball
        ///Ocaso Ball
        ///Sana Ball
        ///Veloz Ball
        ///Gloria Ball
        ///Poción
        ///Antídoto
        ///Antiquemar
        ///Antihielo
        ///Despertar
        ///Antiparalizador
        ///Restaurar Todo
        ///Poción Máxima
        ///Hiperpoción
        ///Superpoción
        ///Cura Total
        ///Revivir
        ///Revivir Máximo
        ///Agua Fresca
        ///Refresco
        ///Limonada
        ///Leche Mu-mu
        ///Polvo Energía
        ///Raíz Energía
        ///Polvo Curación
        ///Hierba Revivir
        ///Éter
        ///Éter Máximo
        ///Elixir
        ///Elixir M [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_es {
            get {
                return ResourceManager.GetString("text_Items_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aucun
        ///Master Ball
        ///Hyper Ball
        ///Super Ball
        ///Poké Ball
        ///Safari Ball
        ///Filet Ball
        ///Scuba Ball
        ///Faiblo Ball
        ///Bis Ball
        ///Chrono Ball
        ///Luxe Ball
        ///Honor Ball
        ///Sombre Ball
        ///Soin Ball
        ///Rapide Ball
        ///Mémoire Ball
        ///Potion
        ///Antidote
        ///Anti-Brûle
        ///Antigel
        ///Réveil
        ///Anti-Para
        ///Guérison
        ///Potion Max
        ///Hyper Potion
        ///Super Potion
        ///Total Soin
        ///Rappel
        ///Rappel Max
        ///Eau Fraîche
        ///Soda Cool
        ///Limonade
        ///Lait Meumeu
        ///Poudrénergie
        ///Racinénergie
        ///Poudre Soin
        ///Herbe Rappel
        ///Huile
        ///Huile Max
        ///Élixir
        ///Élixir Max
        ///Lava Cookie
        ///Jus de Baie
        ///Cend [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_fr {
            get {
                return ResourceManager.GetString("text_Items_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Niente
        ///Master Ball
        ///Ultra Ball
        ///Mega Ball
        ///Poké Ball
        ///Safari Ball
        ///Rete Ball
        ///Sub Ball
        ///Minor Ball
        ///Bis Ball
        ///Timer Ball
        ///Chic Ball
        ///Premier Ball
        ///Scuro Ball
        ///Cura Ball
        ///Velox Ball
        ///Pregio Ball
        ///Pozione
        ///Antidoto
        ///Antiscottatura
        ///Antigelo
        ///Sveglia
        ///Antiparalisi
        ///Ricarica totale
        ///Pozione max
        ///Iperpozione
        ///Superpozione
        ///Cura totale
        ///Revitalizzante
        ///Revitalizzante max
        ///Acqua fresca
        ///Gassosa
        ///Lemonsucco
        ///Latte Mumu
        ///Polvenergia
        ///Radicenergia
        ///Polvocura
        ///Vitalerba
        ///Etere
        ///Etere max
        ///Elisir
        ///Elisir max
        ///Lavottin [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_it {
            get {
                return ResourceManager.GetString("text_Items_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 なし
        ///マスターボール
        ///ハイパーボール
        ///スーパーボール
        ///モンスターボール
        ///サファリボール
        ///ネットボール
        ///ダイブボール
        ///ネストボール
        ///リピートボール
        ///タイマーボール
        ///ゴージャスボール
        ///プレミアボール
        ///ダークボール
        ///ヒールボール
        ///クイックボール
        ///プレシャスボール
        ///キズぐすり
        ///どくけし
        ///やけどなおし
        ///こおりなおし
        ///ねむけざまし
        ///まひなおし
        ///かいふくのくすり
        ///まんたんのくすり
        ///すごいキズぐすり
        ///いいキズぐすり
        ///なんでもなおし
        ///げんきのかけら
        ///げんきのかたまり
        ///おいしいみず
        ///サイコソーダ
        ///ミックスオレ
        ///モーモーミルク
        ///ちからのこな
        ///ちからのねっこ
        ///ばんのうごな
        ///ふっかつそう
        ///ピーピーエイド
        ///ピーピーリカバー
        ///ピーピーエイダー
        ///ピーピーマックス
        ///フエンせんべい
        ///きのみジュース
        ///せいなるはい
        ///マックスアップ
        ///タウリン
        ///ブロムヘキシン
        ///インドメタシン
        ///リゾチウム
        ///ふしぎなアメ
        ///ポイントアップ
        ///キトサン
        ///ポイントマックス
        ///もりのヨウカン
        ///エフェクトガード
        ///クリティカット
        ///プラスパワー
        ///ディフェンダー
        ///スピーダー        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_ja {
            get {
                return ResourceManager.GetString("text_Items_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 없음
        ///마스터볼
        ///하이퍼볼
        ///슈퍼볼
        ///몬스터볼
        ///사파리볼
        ///네트볼
        ///다이브볼
        ///네스트볼
        ///리피트볼
        ///타이머볼
        ///럭셔리볼
        ///프리미어볼
        ///다크볼
        ///힐볼
        ///퀵볼
        ///프레셔스볼
        ///상처약
        ///해독제
        ///화상치료제
        ///얼음상태치료제
        ///잠깨는약
        ///마비치료제
        ///회복약
        ///풀회복약
        ///고급상처약
        ///좋은상처약
        ///만병통치제
        ///기력의조각
        ///기력의덩어리
        ///맛있는물
        ///미네랄사이다
        ///후르츠밀크
        ///튼튼밀크
        ///힘의가루
        ///힘의뿌리
        ///만능가루
        ///부활초
        ///PP에이드
        ///PP회복
        ///PP에이더
        ///PP맥스
        ///용암전병
        ///나무열매쥬스
        ///성스러운분말
        ///맥스업
        ///타우린
        ///사포닌
        ///알칼로이드
        ///리보플라빈
        ///이상한사탕
        ///포인트업
        ///키토산
        ///포인트맥스
        ///숲의양갱
        ///이펙트가드
        ///크리티컬커터
        ///플러스파워
        ///디펜드업
        ///스피드업
        ///잘-맞히기
        ///스페셜업
        ///스페셜가드
        ///삐삐인형
        ///에나비꼬리
        ///파랑비드로
        ///노랑비드로
        ///빨강비드로
        ///검정비드로
        ///하양비드로
        ///여울소금
        ///여울조개껍질
        ///빨강조각
        ///파랑조각
        ///노랑조각
        ///초록조각
        ///실버스프레이
        ///골드스프레이
        ///동굴탈출로프
        ///벌레회피스프레이        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_ko {
            get {
                return ResourceManager.GetString("text_Items_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无
        ///大师球
        ///高级球
        ///超级球
        ///精灵球
        ///狩猎球
        ///捕网球
        ///潜水球
        ///巢穴球
        ///重复球
        ///计时球
        ///豪华球
        ///纪念球
        ///黑暗球
        ///治愈球
        ///先机球
        ///贵重球
        ///伤药
        ///解毒药
        ///灼伤药
        ///解冻药
        ///解眠药
        ///解麻药
        ///全复药
        ///全满药
        ///厉害伤药
        ///好伤药
        ///万灵药
        ///活力碎片
        ///活力块
        ///美味之水
        ///劲爽汽水
        ///果汁牛奶
        ///哞哞鲜奶
        ///元气粉
        ///元气根
        ///万能粉
        ///复活草
        ///ＰＰ单项小补剂
        ///ＰＰ单项全补剂
        ///ＰＰ多项小补剂
        ///ＰＰ多项全补剂
        ///釜炎仙贝
        ///树果汁
        ///圣灰
        ///ＨＰ增强剂
        ///攻击增强剂
        ///防御增强剂
        ///速度增强剂
        ///特攻增强剂
        ///神奇糖果
        ///ＰＰ提升剂
        ///特防增强剂
        ///ＰＰ极限提升剂
        ///森之羊羹
        ///能力防守
        ///要害攻击
        ///力量强化
        ///防御强化
        ///速度强化
        ///命中强化
        ///特攻强化
        ///特防强化
        ///皮皮玩偶
        ///向尾喵的尾巴
        ///蓝色玻璃哨
        ///黄色玻璃哨
        ///红色玻璃哨
        ///黑色玻璃哨
        ///白色玻璃哨
        ///浅滩海盐
        ///浅滩贝壳
        ///红色碎片
        ///蓝色碎片
        ///黄色碎片
        ///绿色碎片
        ///白银喷雾
        ///黄金喷雾
        ///离洞绳
        ///除虫喷雾
        ///日之石
        ///月之石
        ///火之石
        ///雷之石
        ///水之石
        ///叶之石
        ///小蘑菇
        ///大蘑菇
        ///珍珠 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_zh {
            get {
                return ResourceManager.GetString("text_Items_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無
        ///大師球
        ///高級球
        ///超級球
        ///精靈球
        ///狩獵球
        ///捕網球
        ///潛水球
        ///巢穴球
        ///重複球
        ///計時球
        ///豪華球
        ///紀念球
        ///黑暗球
        ///治癒球
        ///先機球
        ///貴重球
        ///傷藥
        ///解毒藥
        ///灼傷藥
        ///解凍藥
        ///解眠藥
        ///解麻藥
        ///全復藥
        ///全滿藥
        ///厲害傷藥
        ///好傷藥
        ///萬靈藥
        ///活力碎片
        ///活力塊
        ///美味之水
        ///勁爽汽水
        ///果汁牛奶
        ///哞哞鮮奶
        ///元氣粉
        ///元氣根
        ///萬能粉
        ///復活草
        ///ＰＰ單項小補劑
        ///ＰＰ單項全補劑
        ///ＰＰ多項小補劑
        ///ＰＰ多項全補劑
        ///釜炎仙貝
        ///樹果汁
        ///聖灰
        ///ＨＰ增強劑
        ///攻擊增強劑
        ///防禦增強劑
        ///速度增強劑
        ///特攻增強劑
        ///神奇糖果
        ///ＰＰ提升劑
        ///特防增強劑
        ///ＰＰ極限提升劑
        ///森之羊羹
        ///能力防守
        ///要害攻擊
        ///力量強化
        ///防禦強化
        ///速度強化
        ///命中強化
        ///特攻強化
        ///特防強化
        ///皮皮玩偶
        ///向尾喵的尾巴
        ///藍色玻璃哨
        ///黃色玻璃哨
        ///紅色玻璃哨
        ///黑色玻璃哨
        ///白色玻璃哨
        ///淺灘海鹽
        ///淺灘貝殼
        ///紅色碎片
        ///藍色碎片
        ///黃色碎片
        ///綠色碎片
        ///白銀噴霧
        ///黃金噴霧
        ///離洞繩
        ///除蟲噴霧
        ///日之石
        ///月之石
        ///火之石
        ///雷之石
        ///水之石
        ///葉之石
        ///小蘑菇
        ///大蘑菇
        ///珍珠 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Items_zh2 {
            get {
                return ResourceManager.GetString("text_Items_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ―――――
        ///拍击
        ///空手劈
        ///连环巴掌
        ///连续拳
        ///百万吨重拳
        ///聚宝功
        ///火焰拳
        ///冰冻拳
        ///雷电拳
        ///抓
        ///夹住
        ///极落钳
        ///旋风刀
        ///剑舞
        ///居合劈
        ///起风
        ///翅膀攻击
        ///吹飞
        ///飞翔
        ///绑紧
        ///摔打
        ///藤鞭
        ///踩踏
        ///二连踢
        ///百万吨重踢
        ///飞踢
        ///回旋踢
        ///泼沙
        ///头锤
        ///角撞
        ///乱击
        ///角钻
        ///撞击
        ///泰山压顶
        ///紧束
        ///猛撞
        ///大闹一番
        ///舍身冲撞
        ///摇尾巴
        ///毒针
        ///双针
        ///飞弹针
        ///瞪眼
        ///咬住
        ///叫声
        ///吼叫
        ///唱歌
        ///超音波
        ///音爆
        ///定身法
        ///溶解液
        ///火花
        ///喷射火焰
        ///白雾
        ///水枪
        ///水炮
        ///冲浪
        ///冰冻光束
        ///暴风雪
        ///幻象光线
        ///泡沫光线
        ///极光束
        ///破坏光线
        ///啄
        ///啄钻
        ///深渊翻滚
        ///踢倒
        ///双倍奉还
        ///地球上投
        ///怪力
        ///吸取
        ///超级吸取
        ///寄生种子
        ///生长
        ///飞叶快刀
        ///日光束
        ///毒粉
        ///麻痹粉
        ///催眠粉
        ///花瓣舞
        ///吐丝
        ///龙之怒
        ///火焰旋涡
        ///电击
        ///十万伏特
        ///电磁波
        ///打雷
        ///落石
        ///地震
        ///地裂
        ///挖洞
        ///剧毒
        ///念力
        ///精神强念
        ///催眠术
        ///瑜伽姿势
        ///高速移动
        ///电光一闪
        ///愤怒
        ///瞬间移动
        ///黑夜魔影
        ///模仿
        ///刺耳声
        ///影子分身
        ///自我再生
        ///变硬        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Moves_zh {
            get {
                return ResourceManager.GetString("text_Moves_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ―――――
        ///拍擊
        ///空手劈
        ///連環巴掌
        ///連續拳
        ///百萬噸重拳
        ///聚寶功
        ///火焰拳
        ///冰凍拳
        ///雷電拳
        ///抓
        ///夾住
        ///斷頭鉗
        ///旋風刀
        ///劍舞
        ///居合斬
        ///起風
        ///翅膀攻擊
        ///吹飛
        ///飛翔
        ///綁緊
        ///摔打
        ///藤鞭
        ///踩踏
        ///二連踢
        ///百萬噸重踢
        ///飛踢
        ///迴旋踢
        ///潑沙
        ///頭錘
        ///角撞
        ///亂擊
        ///角鑽
        ///撞擊
        ///泰山壓頂
        ///緊束
        ///猛撞
        ///大鬧一番
        ///捨身衝撞
        ///搖尾巴
        ///毒針
        ///雙針
        ///飛彈針
        ///瞪眼
        ///咬住
        ///叫聲
        ///吼叫
        ///唱歌
        ///超音波
        ///音爆
        ///定身法
        ///溶解液
        ///火花
        ///噴射火焰
        ///白霧
        ///水槍
        ///水炮
        ///衝浪
        ///冰凍光束
        ///暴風雪
        ///幻象光線
        ///泡沫光線
        ///極光束
        ///破壞光線
        ///啄
        ///啄鑽
        ///地獄翻滾
        ///踢倒
        ///雙倍奉還
        ///地球上投
        ///怪力
        ///吸取
        ///超級吸取
        ///寄生種子
        ///生長
        ///飛葉快刀
        ///日光束
        ///毒粉
        ///麻痺粉
        ///催眠粉
        ///花瓣舞
        ///吐絲
        ///龍之怒
        ///火焰旋渦
        ///電擊
        ///十萬伏特
        ///電磁波
        ///打雷
        ///落石
        ///地震
        ///地裂
        ///挖洞
        ///劇毒
        ///念力
        ///精神強念
        ///催眠術
        ///瑜伽姿勢
        ///高速移動
        ///電光一閃
        ///憤怒
        ///瞬間移動
        ///黑夜魔影
        ///模仿
        ///刺耳聲
        ///影子分身
        ///自我再生
        ///變硬        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Moves_zh2 {
            get {
                return ResourceManager.GetString("text_Moves_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勤奋
        ///怕寂寞
        ///勇敢
        ///固执
        ///顽皮
        ///大胆
        ///坦率
        ///悠闲
        ///淘气
        ///乐天
        ///胆小
        ///急躁
        ///认真
        ///爽朗
        ///天真
        ///内敛
        ///慢吞吞
        ///冷静
        ///害羞
        ///马虎
        ///温和
        ///温顺
        ///自大
        ///慎重
        ///浮躁 的本地化字符串。
        /// </summary>
        internal static string text_Natures_zh {
            get {
                return ResourceManager.GetString("text_Natures_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勤奮
        ///怕寂寞
        ///勇敢
        ///固執
        ///頑皮
        ///大膽
        ///坦率
        ///悠閒
        ///淘氣
        ///樂天
        ///膽小
        ///急躁
        ///認真
        ///爽朗
        ///天真
        ///內斂
        ///慢吞吞
        ///冷靜
        ///害羞
        ///馬虎
        ///溫和
        ///溫順
        ///自大
        ///慎重
        ///浮躁 的本地化字符串。
        /// </summary>
        internal static string text_Natures_zh2 {
            get {
                return ResourceManager.GetString("text_Natures_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宝可方块盒
        ///树果混合器
        ///给与一个宝可方块
        ///给与
        ///制作宝可方块
        ///制作
        ///[~ 6]
        ///颜色
        ///[VAR NUM3(0000)]
        ///[VAR PKNICK(0000)]
        ///[VAR MOVE(0000)]
        ///给哪个宝可梦？
        ///你把宝可方块给了[VAR PKNICK(0000)]！
        ///请选择筛选颜色
        ///选择一个宝可方块
        ///要对宝可方块做些什么？
        ///选择需要混合的树果
        ///[~ 17]
        ///你做出了[VAR 01A3(0000)]个[VAR NUM1(0001)]！[VAR BE05(0000)][VAR BE05(0001)]
        ///把宝可方块给[VAR PKNICK(0000)]？
        ///蛋不能吃宝可方块！
        ///给哪个宝可梦？
        ///你不能混合超过4个树果！
        ///按红色筛选
        ///按蓝色筛选
        ///按粉色筛选
        ///按绿色筛选
        ///按黄色筛选
        ///开始混合
        ///返回树果
        ///给与
        ///退出
        ///是
        ///否
        ///全部
        ///红
        ///蓝
        ///粉
        ///绿
        ///黄
        ///[~ 40]
        ///[~ 41]
        ///[~ 42]
        ///[~ 43]
        ///[~ 44]
        ///[~ 45]
        ///[~ 46]
        ///[~ 47]
        ///[~ 48]
        ///[~ 49]
        ///[~ 50]
        ///[VAR 01A3(0000) [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Pokeblock_zh {
            get {
                return ResourceManager.GetString("text_Pokeblock_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寶可方塊盒
        ///樹果混合器
        ///給與一個寶可方塊
        ///給與
        ///製作寶可方塊
        ///製作
        ///[~ 6]
        ///顏色
        ///[VAR NUM3(0000)]
        ///[VAR PKNICK(0000)]
        ///[VAR MOVE(0000)]
        ///給哪個精靈？
        ///你把寶可方塊給了[VAR PKNICK(0000)]！
        ///請選擇篩選顏色
        ///選擇一個寶可方塊
        ///要對寶可方塊做些甚麼？
        ///選擇需要混合的樹果
        ///[~ 17]
        ///你做出了[VAR 01A3(0000)]個[VAR NUM1(0001)]！[VAR BE05(0000)][VAR BE05(0001)]
        ///把寶可方塊給[VAR PKNICK(0000)]？
        ///蛋不能吃寶可方塊！
        ///給哪個精靈？
        ///你不能混合超過4個樹果！
        ///按紅色篩選
        ///按藍色篩選
        ///按粉色篩選
        ///按綠色篩選
        ///按黃色篩選
        ///開始混合
        ///返回樹果
        ///給與
        ///退出
        ///是
        ///否
        ///全部
        ///紅
        ///藍
        ///粉
        ///綠
        ///黃
        ///[~ 40]
        ///[~ 41]
        ///[~ 42]
        ///[~ 43]
        ///[~ 44]
        ///[~ 45]
        ///[~ 46]
        ///[~ 47]
        ///[~ 48]
        ///[~ 49]
        ///[~ 50]
        ///[VAR 01A3(0000)]        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Pokeblock_zh2 {
            get {
                return ResourceManager.GetString("text_Pokeblock_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///甘甜泡芙
        ///清新泡芙
        ///酸涩泡芙
        ///苦甜泡芙
        ///香辣泡芙
        ///珍奇甘甜泡芙
        ///珍奇清新泡芙
        ///珍奇酸涩泡芙
        ///珍奇苦甜泡芙
        ///珍奇香辣泡芙
        ///浓郁甘甜泡芙
        ///浓郁清新泡芙
        ///浓郁酸涩泡芙
        ///浓郁苦甜泡芙
        ///浓郁香辣泡芙
        ///细致甘甜泡芙
        ///细致清新泡芙
        ///细致酸涩泡芙
        ///细致苦甜泡芙
        ///细致香辣泡芙
        ///豪华生日泡芙
        ///豪华纪念泡芙
        ///豪华春天泡芙
        ///豪华夏天泡芙
        ///豪华秋天泡芙
        ///豪华冬天泡芙 的本地化字符串。
        /// </summary>
        internal static string text_Puff_zh {
            get {
                return ResourceManager.GetString("text_Puff_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///甘甜泡芙
        ///清新泡芙
        ///酸澀泡芙
        ///苦甜泡芙
        ///香辣泡芙
        ///珍奇甘甜泡芙
        ///珍奇清新泡芙
        ///珍奇酸澀泡芙
        ///珍奇苦甜泡芙
        ///珍奇香辣泡芙
        ///濃郁甘甜泡芙
        ///濃郁清新泡芙
        ///濃郁酸澀泡芙
        ///濃郁苦甜泡芙
        ///濃郁香辣泡芙
        ///細緻甘甜泡芙
        ///細緻清新泡芙
        ///細緻酸澀泡芙
        ///細緻苦甜泡芙
        ///細緻香辣泡芙
        ///豪華生日泡芙
        ///豪華紀念泡芙
        ///豪華春天泡芙
        ///豪華夏天泡芙
        ///豪華秋天泡芙
        ///豪華冬天泡芙 的本地化字符串。
        /// </summary>
        internal static string text_Puff_zh2 {
            get {
                return ResourceManager.GetString("text_Puff_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RibbonChampionKalos	卡洛斯冠军奖章
        ///RibbonChampionG3	冠军奖章 (3代)
        ///RibbonChampionSinnoh	神奥冠军奖章
        ///RibbonBestFriends	好友奖章
        ///RibbonTraining	修行奖章
        ///RibbonBattlerSkillful	高手对战奖章
        ///RibbonBattlerExpert	大师对战奖章
        ///RibbonEffort	努力奖章
        ///RibbonAlert	振奋奖章
        ///RibbonShock	心跳奖章
        ///RibbonDowncast	失望奖章
        ///RibbonCareless	大意奖章
        ///RibbonRelax	畅快奖章
        ///RibbonSnooze	酣睡奖章
        ///RibbonSmile	欢笑奖章
        ///RibbonGorgeous	豪华奖章
        ///RibbonRoyal	高贵奖章
        ///RibbonGorgeousRoyal	豪华高贵奖章
        ///RibbonArtist	肖像奖章
        ///RibbonFootprint	脚印奖章
        ///RibbonRecord	纪录奖章
        ///RibbonLegend	传说奖章
        ///RibbonCountry	地区奖章
        ///Ribbo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Ribbons_zh {
            get {
                return ResourceManager.GetString("text_Ribbons_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RibbonChampionKalos	卡洛斯冠軍
        ///RibbonChampionG3	冠軍 (Gen3)
        ///RibbonChampionSinnoh	神奧冠軍
        ///RibbonBestFriends	好友
        ///RibbonTraining	修行
        ///RibbonBattlerSkillful	高手對戰
        ///RibbonBattlerExpert	大師對戰
        ///RibbonEffort	努力
        ///RibbonAlert	振奮
        ///RibbonShock	心跳
        ///RibbonDowncast	失望
        ///RibbonCareless	大意
        ///RibbonRelax	暢快
        ///RibbonSnooze	酣睡
        ///RibbonSmile	歡笑
        ///RibbonGorgeous	豪華
        ///RibbonRoyal	高貴
        ///RibbonGorgeousRoyal	豪華高貴
        ///RibbonArtist	肖像
        ///RibbonFootprint	腳印
        ///RibbonRecord	紀錄
        ///RibbonLegend	傳說
        ///RibbonCountry	地區
        ///RibbonNational	國家
        ///RibbonEarth	地球
        ///RibbonWorld	世界 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Ribbons_zh2 {
            get {
                return ResourceManager.GetString("text_Ribbons_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蛋
        ///妙蛙种子
        ///妙蛙草
        ///妙蛙花
        ///小火龙
        ///火恐龙
        ///喷火龙
        ///杰尼龟
        ///卡咪龟
        ///水箭龟
        ///绿毛虫
        ///铁甲蛹
        ///巴大蝶
        ///独角虫
        ///铁壳蛹
        ///大针蜂
        ///波波
        ///比比鸟
        ///大比鸟
        ///小拉达
        ///拉达
        ///烈雀
        ///大嘴雀
        ///阿柏蛇
        ///阿柏怪
        ///皮卡丘
        ///雷丘
        ///穿山鼠
        ///穿山王
        ///尼多兰
        ///尼多娜
        ///尼多后
        ///尼多朗
        ///尼多力诺
        ///尼多王
        ///皮皮
        ///皮可西
        ///六尾
        ///九尾
        ///胖丁
        ///胖可丁
        ///超音蝠
        ///大嘴蝠
        ///走路草
        ///臭臭花
        ///霸王花
        ///派拉斯
        ///派拉斯特
        ///毛球
        ///摩鲁蛾
        ///地鼠
        ///三地鼠
        ///喵喵
        ///猫老大
        ///可达鸭
        ///哥达鸭
        ///猴怪
        ///火暴猴
        ///卡蒂狗
        ///风速狗
        ///蚊香蝌蚪
        ///蚊香君
        ///蚊香泳士
        ///凯西
        ///勇基拉
        ///胡地
        ///腕力
        ///豪力
        ///怪力
        ///喇叭芽
        ///口呆花
        ///大食花
        ///玛瑙水母
        ///毒刺水母
        ///小拳石
        ///隆隆石
        ///隆隆岩
        ///小火马
        ///烈焰马
        ///呆呆兽
        ///呆壳兽
        ///小磁怪
        ///三合一磁怪
        ///大葱鸭
        ///嘟嘟
        ///嘟嘟利
        ///小海狮
        ///白海狮
        ///臭泥
        ///臭臭泥
        ///大舌贝
        ///刺甲贝
        ///鬼斯
        ///鬼斯通
        ///耿鬼
        ///大岩蛇
        ///催眠貘
        ///引梦貘人
        ///大钳蟹
        ///巨钳蟹
        ///霹雳电球
        ///顽皮雷弹
        ///蛋蛋
        ///椰蛋树
        ///卡拉卡拉 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Species_zh {
            get {
                return ResourceManager.GetString("text_Species_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蛋
        ///妙蛙種子
        ///妙蛙草
        ///妙蛙花
        ///小火龍
        ///火恐龍
        ///噴火龍
        ///傑尼龜
        ///卡咪龜
        ///水箭龜
        ///綠毛蟲
        ///鐵甲蛹
        ///巴大蝶
        ///獨角蟲
        ///鐵殼蛹
        ///大針蜂
        ///波波
        ///比比鳥
        ///大比鳥
        ///小拉達
        ///拉達
        ///烈雀
        ///大嘴雀
        ///阿柏蛇
        ///阿柏怪
        ///皮卡丘
        ///雷丘
        ///穿山鼠
        ///穿山王
        ///尼多蘭
        ///尼多娜
        ///尼多后
        ///尼多朗
        ///尼多力諾
        ///尼多王
        ///皮皮
        ///皮可西
        ///六尾
        ///九尾
        ///胖丁
        ///胖可丁
        ///超音蝠
        ///大嘴蝠
        ///走路草
        ///臭臭花
        ///霸王花
        ///派拉斯
        ///派拉斯特
        ///毛球
        ///摩魯蛾
        ///地鼠
        ///三地鼠
        ///喵喵
        ///貓老大
        ///可達鴨
        ///哥達鴨
        ///猴怪
        ///火爆猴
        ///卡蒂狗
        ///風速狗
        ///蚊香蝌蚪
        ///蚊香君
        ///蚊香泳士
        ///凱西
        ///勇基拉
        ///胡地
        ///腕力
        ///豪力
        ///怪力
        ///喇叭芽
        ///口呆花
        ///大食花
        ///瑪瑙水母
        ///毒刺水母
        ///小拳石
        ///隆隆石
        ///隆隆岩
        ///小火馬
        ///烈焰馬
        ///呆呆獸
        ///呆殼獸
        ///小磁怪
        ///三合一磁怪
        ///大蔥鴨
        ///嘟嘟
        ///嘟嘟利
        ///小海獅
        ///白海獅
        ///臭泥
        ///臭臭泥
        ///大舌貝
        ///刺甲貝
        ///鬼斯
        ///鬼斯通
        ///耿鬼
        ///大岩蛇
        ///催眠貘
        ///引夢貘人
        ///大鉗蟹
        ///巨鉗蟹
        ///霹靂電球
        ///頑皮雷彈
        ///蛋蛋
        ///椰蛋樹
        ///卡拉卡拉 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string text_Species_zh2 {
            get {
                return ResourceManager.GetString("text_Species_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试验训练！粉蛹
        ///粉蝶蛹！精力射门
        ///特攻训练 VS小磁怪
        ///HP训练 VS吼吼鲸
        ///攻击训练 VS牙牙
        ///特防训练 VS玛瑙水母
        ///速度训练 VS嗡蝠
        ///防御训练 VS小拳石
        ///追踪射门！三合一磁怪
        ///古空棘鱼的机会球门！
        ///连珠射门！斧牙龙
        ///毒刺水母与小气球！
        ///高速射门！化石翼龙
        ///打破隆隆石的封锁！
        ///甩开！魔球的自爆磁怪
        ///迎击！巨大吼鲸王
        ///看穿！猛攻的双斧战龙
        ///冲散！毒拉蜜妮军团
        ///抓住！疾风的音波龙
        ///击破！隆隆岩防卫线
        ///一波未平一波又起！？
        ///一等奖品 叶之石！
        ///一等奖品 火之石！
        ///一等奖品 水之石！
        ///追踪逃跑的球门！
        ///反击的后半战！
        ///速攻的前半战！
        ///纵横无尽的远距离射门！
        ///逆袭的粉蛹！
        ///弹幕 弹幕 小气球！
        ///骤死 三头龙！
        ///最强决定战！
        ///恐怖！大颚双尾
        ///被打开的禁断拉链！
        ///铁腕 钢腕 巨钳打击！
        ///念力！汤匙乱舞
        ///暴富！出世 鲤鱼王
        ///惊异！连续百万进化！ 的本地化字符串。
        /// </summary>
        internal static string text_SuperTraining_zh {
            get {
                return ResourceManager.GetString("text_SuperTraining_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 試驗訓練！粉蛹
        ///粉蝶蛹！精力射門
        ///特攻訓練 VS小磁怪
        ///HP訓練 VS吼吼鯨
        ///攻擊訓練 VS牙牙
        ///特防訓練 VS瑪瑙水母
        ///速度訓練 VS嗡蝠
        ///防禦訓練 VS小拳石
        ///追蹤射門！三合一磁怪
        ///古空棘魚的機會球門！
        ///連珠射門！斧牙龍
        ///毒刺水母與小氣球！
        ///高速射門！化石翼龍
        ///打破隆隆石的封鎖！
        ///甩開！魔球的自爆磁怪
        ///迎擊！巨大吼鯨王
        ///看穿！猛攻的雙斧戰龍
        ///沖散！毒拉蜜妮軍團
        ///抓住！疾風的音波龍
        ///擊破！隆隆岩防衛線
        ///一波未平一波又起！？
        ///一等獎品 葉之石！
        ///一等獎品 火之石！
        ///一等獎品 水之石！
        ///追蹤逃跑的球門！
        ///反擊的後半戰！
        ///速攻的前半戰！
        ///縱橫無盡的遠距離射門！
        ///逆襲的粉蛹！
        ///彈幕 彈幕 小氣球！
        ///驟死 三頭龍！
        ///最強決定戰！
        ///恐怖！大顎雙尾
        ///被打開的禁斷拉鍊！
        ///鐵腕 鋼腕 巨鉗打擊！
        ///念力！湯匙亂舞
        ///暴富！出世 鯉魚王
        ///驚異！連續Mega進化！ 的本地化字符串。
        /// </summary>
        internal static string text_SuperTraining_zh2 {
            get {
                return ResourceManager.GetString("text_SuperTraining_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///HP沙袋S
        ///HP沙袋M
        ///HP沙袋L
        ///攻击沙袋S
        ///攻击沙袋M
        ///攻击沙袋L
        ///防御沙袋S
        ///防御沙袋M
        ///防御沙袋L
        ///特攻沙袋S
        ///特攻沙袋M
        ///特攻沙袋L
        ///特防沙袋S
        ///特防沙袋M
        ///特防沙袋L
        ///速度沙袋S
        ///速度沙袋M
        ///速度沙袋L
        ///力量UP沙袋
        ///防御UP沙袋
        ///移动UP沙袋
        ///大小UP沙袋
        ///加倍UP沙袋
        ///闪焰队沙袋
        ///全新沙袋
        ///放松沙袋 的本地化字符串。
        /// </summary>
        internal static string text_TrainingBag_zh {
            get {
                return ResourceManager.GetString("text_TrainingBag_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///HP沙袋S
        ///HP沙袋M
        ///HP沙袋L
        ///攻擊沙袋S
        ///攻擊沙袋M
        ///攻擊沙袋L
        ///防禦沙袋S
        ///防禦沙袋M
        ///防禦沙袋L
        ///特攻沙袋S
        ///特攻沙袋M
        ///特攻沙袋L
        ///特防沙袋S
        ///特防沙袋M
        ///特防沙袋L
        ///速度沙袋S
        ///速度沙袋M
        ///速度沙袋L
        ///力量UP沙袋
        ///防禦UP沙袋
        ///移動UP沙袋
        ///大小UP沙袋
        ///加倍UP沙袋
        ///閃焰隊沙袋
        ///全新沙袋
        ///放鬆沙袋 的本地化字符串。
        /// </summary>
        internal static string text_TrainingBag_zh2 {
            get {
                return ResourceManager.GetString("text_TrainingBag_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般
        ///格斗
        ///飞行
        ///毒
        ///地面
        ///岩石
        ///虫
        ///幽灵
        ///钢
        ///火
        ///水
        ///草
        ///电
        ///超能力
        ///冰
        ///龙
        ///恶
        ///妖精
        ///星晶 的本地化字符串。
        /// </summary>
        internal static string text_Types_zh {
            get {
                return ResourceManager.GetString("text_Types_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般
        ///格鬥
        ///飛行
        ///毒
        ///地面
        ///岩石
        ///蟲
        ///幽靈
        ///鋼
        ///火
        ///水
        ///草
        ///電
        ///超能力
        ///冰
        ///龍
        ///惡
        ///妖精
        ///星晶 的本地化字符串。
        /// </summary>
        internal static string text_Types_zh2 {
            get {
                return ResourceManager.GetString("text_Types_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 森林
        ///城市
        ///沙漠
        ///热带草原
        ///石山
        ///火山
        ///雪山
        ///洞窟
        ///海滨
        ///海底
        ///河川
        ///天空
        ///宝可梦中心
        ///金属
        ///方格
        ///朴素
        ///特典１
        ///特典２
        ///特典３
        ///特典４
        ///特典５
        ///特典６
        ///特典７
        ///特典８
        ///特典９
        ///特典１０
        ///特典１１
        ///特典１２
        ///特典１３
        ///特典１４
        ///特典１５
        ///特典１６ 的本地化字符串。
        /// </summary>
        internal static string text_Wallpaper_zh {
            get {
                return ResourceManager.GetString("text_Wallpaper_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 森林
        ///城市
        ///沙漠
        ///熱帶草原
        ///石山
        ///火山
        ///雪山
        ///洞窟
        ///海濱
        ///海底
        ///河川
        ///天空
        ///寶可夢中心
        ///金屬
        ///方格
        ///樸素
        ///特典１
        ///特典２
        ///特典３
        ///特典４
        ///特典５
        ///特典６
        ///特典７
        ///特典８
        ///特典９
        ///特典１０
        ///特典１１
        ///特典１２
        ///特典１３
        ///特典１４
        ///特典１５
        ///特典１６ 的本地化字符串。
        /// </summary>
        internal static string text_Wallpaper_zh2 {
            get {
                return ResourceManager.GetString("text_Wallpaper_zh2", resourceCulture);
            }
        }
    }
}
